export class Game {
    id: Number;

    aa: Number = 0;
    ab: Number = 0;
    ac: Number = 0;
    ad: Number = 0;
    ae: Number = 0;
    af: Number = 0;
    ag: Number = 0;
    ah: Number = 0;
    ba: Number = 0;
    bb: Number = 0;
    bc: Number = 0;
    bd: Number = 0;
    be: Number = 0;
    bf: Number = 0;
    bg: Number = 0;
    bh: Number = 0;
    ca: Number = 0;
    cb: Number = 0;
    cc: Number = 0;
    cd: Number = 0;
    ce: Number = 0;
    cf: Number = 0;
    cg: Number = 0;
    ch: Number = 0;
    da: Number = 0;
    db: Number = 0;
    dc: Number = 0;
    dd: Number = 0;
    de: Number = 0;
    df: Number = 0;
    dg: Number = 0;
    dh: Number = 0;
    ea: Number = 0;
    eb: Number = 0;
    ec: Number = 0;
    ed: Number = 0;
    ee: Number = 0;
    ef: Number = 0;
    eg: Number = 0;
    eh: Number = 0;
    fa: Number = 0;
    fb: Number = 0;
    fc: Number = 0;
    fd: Number = 0;
    fe: Number = 0;
    ff: Number = 0;
    fg: Number = 0;
    fh: Number = 0;
    ga: Number = 0;
    gb: Number = 0;
    gc: Number = 0;
    gd: Number = 0;
    ge: Number = 0;
    gf: Number = 0;
    gg: Number = 0;
    gh: Number = 0;
    ha: Number = 0;
    hb: Number = 0;
    hc: Number = 0;
    hd: Number = 0;
    he: Number = 0;
    hf: Number = 0;
    hg: Number = 0;
    hh: Number = 0;

    constructor() {
        this.dd = 1;
        this.de = 2;
        this.ed = 2;
        this.ee = 1;
    }
}